name: Test

on:
  - pull_request

permissions:
  contents: read

env:
  BUNDLE_WITHOUT: release

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
          - ruby: "3.3"
          - ruby: "3.4"
            coverage: "yes"
    env:
      COVERAGE: ${{ matrix.coverage }}
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
      - name: Run spec tests
        run: bundle exec rake

  tests:
    needs:
      - rubocop
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
